### ISSUE TITLE
Muzei crashes when reloading wallpapers

### ISSUE THREAD

**Issue by helloimreallysadistic** [jahirfiquitiva/Frames#178]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Frames Version: `3.3.2`
 - Android version: `10`
 - Device Manufacturer: `Google`
 - Device Name: `Google Pixel 3a`

### Describe the bug
Muzei crashes when trying to reload wallpapers from dashboard app

### Reproduction Steps
Reproducible on latest sample dashboard app

1. Open Muzei
2. Go to Sources tab
3. Select dashboard app > Browse
4. Three Dot Menu > Refresh
5. Crashes on this part

### Expected behavior

Clicking refresh will refresh list of wallpapers inside Muzei

```Gradle
java.lang.IllegalStateException: Cannot invoke removeObservers on a background thread
        at androidx.lifecycle.LiveData.assertMainThread(LiveData.java:462)
        at androidx.lifecycle.LiveData.removeObservers(LiveData.java:259)
        at dev.jahir.frames.data.viewmodels.WallpapersDataViewModel.destroy(WallpapersDataViewModel.kt:305)
        at dev.jahir.frames.muzei.FramesArtWorker.destroy$library_debug(FramesArtWorker.kt:75)
        at dev.jahir.frames.muzei.FramesArtWorker.destroy$library_debug$default(FramesArtWorker.kt:74)
        at dev.jahir.frames.muzei.FramesArtWorker.loadWallpapers(FramesArtWorker.kt:34)
        at dev.jahir.frames.muzei.FramesArtProvider.onLoadRequested(FramesArtProvider.kt:29)
        at com.google.android.apps.muzei.api.provider.MuzeiArtProvider.call(MuzeiArtProvider.java:427)
        at android.content.ContentProvider.call(ContentProvider.java:2152)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:477)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:277)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
```

**Comment by jahirfiquitiva** [comment]
Should be fixed with v `3.3.3`
