### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by Mauyed** [jahirfiquitiva/Frames#98]
- [ T ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ T ] I have verified that I am using the latest version.

### Device/App info:
 - Frames Version: `2.5.3`
 - Android version: `8.0`
 - Device Manufacturer: `Samsung`
 - Device Name: `S9+`

### Describe the bug
I tried to enable the notification service and I don't know what happened it crashes every time I send a notification from onesignal i totally followed the steps in the wiki

### Expected behavior
it should work fine

### Screenshots
I'll post a video if you need further info

### Code and/or Logs [ are from Logcat ]
`12-11 20:50:57.433 2134-2134/com.mauyed.wallpapers E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mauyed.wallpapers, PID: 2134
    java.lang.RuntimeException: Unable to instantiate service jahirfiquitiva.apps.frames.sample.NotificationService: java.lang.ClassNotFoundException: Didn't find class "jahirfiquitiva.apps.frames.sample.NotificationService" on path: DexPathList[[zip file "/data/app/com.mauyed.wallpapers-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2746)
        at android.app.ActivityThread.access$1800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1386)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "jahirfiquitiva.apps.frames.sample.NotificationService" on path: DexPathList[[zip file "/data/app/com.mauyed.wallpapers-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2743)
        at android.app.ActivityThread.access$1800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1386) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
    	Suppressed: java.lang.ClassNotFoundException: jahirfiquitiva.apps.frames.sample.NotificationService
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 11 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available`

**Comment by jahirfiquitiva** [comment]
Read the wiki. Once you change your app package, be sure to update the `AndroidManifest.xml` so the app can find the right components
